/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CatalogCategoryCreateNestedManyWithoutMerchantsInput } from "./CatalogCategoryCreateNestedManyWithoutMerchantsInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CatalogItemCreateNestedManyWithoutMerchantsInput } from "./CatalogItemCreateNestedManyWithoutMerchantsInput";
import { CatalogCreateNestedManyWithoutMerchantsInput } from "./CatalogCreateNestedManyWithoutMerchantsInput";
import { CatalogModifierGroupCreateNestedManyWithoutMerchantsInput } from "./CatalogModifierGroupCreateNestedManyWithoutMerchantsInput";
import { CatalogItemModifierCreateNestedManyWithoutMerchantsInput } from "./CatalogItemModifierCreateNestedManyWithoutMerchantsInput";

@InputType()
class MerchantCreateInput {
  @ApiProperty({
    required: false,
    type: () => CatalogCategoryCreateNestedManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogCategoryCreateNestedManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogCategoryCreateNestedManyWithoutMerchantsInput, {
    nullable: true,
  })
  catalogCategories?: CatalogCategoryCreateNestedManyWithoutMerchantsInput;

  @ApiProperty({
    required: false,
    type: () => CatalogItemCreateNestedManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogItemCreateNestedManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogItemCreateNestedManyWithoutMerchantsInput, {
    nullable: true,
  })
  catalogItems?: CatalogItemCreateNestedManyWithoutMerchantsInput;

  @ApiProperty({
    required: false,
    type: () => CatalogCreateNestedManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogCreateNestedManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogCreateNestedManyWithoutMerchantsInput, {
    nullable: true,
  })
  catalogs?: CatalogCreateNestedManyWithoutMerchantsInput;

  @ApiProperty({
    required: false,
    type: () => CatalogModifierGroupCreateNestedManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogModifierGroupCreateNestedManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogModifierGroupCreateNestedManyWithoutMerchantsInput, {
    nullable: true,
  })
  modifierGroups?: CatalogModifierGroupCreateNestedManyWithoutMerchantsInput;

  @ApiProperty({
    required: false,
    type: () => CatalogItemModifierCreateNestedManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogItemModifierCreateNestedManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogItemModifierCreateNestedManyWithoutMerchantsInput, {
    nullable: true,
  })
  modifiers?: CatalogItemModifierCreateNestedManyWithoutMerchantsInput;
}

export { MerchantCreateInput as MerchantCreateInput };
