/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CatalogCategoryUpdateManyWithoutMerchantsInput } from "./CatalogCategoryUpdateManyWithoutMerchantsInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { CatalogItemUpdateManyWithoutMerchantsInput } from "./CatalogItemUpdateManyWithoutMerchantsInput";
import { CatalogUpdateManyWithoutMerchantsInput } from "./CatalogUpdateManyWithoutMerchantsInput";
import { CatalogModifierGroupUpdateManyWithoutMerchantsInput } from "./CatalogModifierGroupUpdateManyWithoutMerchantsInput";
import { CatalogItemModifierUpdateManyWithoutMerchantsInput } from "./CatalogItemModifierUpdateManyWithoutMerchantsInput";

@InputType()
class MerchantUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CatalogCategoryUpdateManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogCategoryUpdateManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogCategoryUpdateManyWithoutMerchantsInput, {
    nullable: true,
  })
  catalogCategories?: CatalogCategoryUpdateManyWithoutMerchantsInput;

  @ApiProperty({
    required: false,
    type: () => CatalogItemUpdateManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogItemUpdateManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogItemUpdateManyWithoutMerchantsInput, {
    nullable: true,
  })
  catalogItems?: CatalogItemUpdateManyWithoutMerchantsInput;

  @ApiProperty({
    required: false,
    type: () => CatalogUpdateManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogUpdateManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogUpdateManyWithoutMerchantsInput, {
    nullable: true,
  })
  catalogs?: CatalogUpdateManyWithoutMerchantsInput;

  @ApiProperty({
    required: false,
    type: () => CatalogModifierGroupUpdateManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogModifierGroupUpdateManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogModifierGroupUpdateManyWithoutMerchantsInput, {
    nullable: true,
  })
  modifierGroups?: CatalogModifierGroupUpdateManyWithoutMerchantsInput;

  @ApiProperty({
    required: false,
    type: () => CatalogItemModifierUpdateManyWithoutMerchantsInput,
  })
  @ValidateNested()
  @Type(() => CatalogItemModifierUpdateManyWithoutMerchantsInput)
  @IsOptional()
  @Field(() => CatalogItemModifierUpdateManyWithoutMerchantsInput, {
    nullable: true,
  })
  modifiers?: CatalogItemModifierUpdateManyWithoutMerchantsInput;
}

export { MerchantUpdateInput as MerchantUpdateInput };
