/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  ValidateNested,
  IsOptional,
  IsInt,
  IsNumber,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Merchant } from "../../merchant/base/Merchant";
import { CatalogModifierGroup } from "../../catalogModifierGroup/base/CatalogModifierGroup";
import { EnumCatalogItemModifierType } from "./EnumCatalogItemModifierType";

@ObjectType()
class CatalogItemModifier {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  description!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    type: () => Merchant,
  })
  @ValidateNested()
  @Type(() => Merchant)
  merchant?: Merchant;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  modifierGroupId!: string | null;

  @ApiProperty({
    required: false,
    type: () => [CatalogModifierGroup],
  })
  @ValidateNested()
  @Type(() => CatalogModifierGroup)
  @IsOptional()
  modifierGroups?: Array<CatalogModifierGroup>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  posIntegrationId!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  price!: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  suspendedUntil!: number | null;

  @ApiProperty({
    required: true,
    enum: EnumCatalogItemModifierType,
  })
  @IsEnum(EnumCatalogItemModifierType)
  @Field(() => EnumCatalogItemModifierType, {
    nullable: true,
  })
  type?:
    | "ALCOHOL"
    | "FOOD"
    | "REGULAR"
    | "SCHEDULED_SERVICE"
    | "ON_DEMAND_SERVICE";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { CatalogItemModifier as CatalogItemModifier };
