/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  IsInt,
  IsNumber,
  IsEnum,
} from "class-validator";
import { MerchantWhereUniqueInput } from "../../merchant/base/MerchantWhereUniqueInput";
import { Type } from "class-transformer";
import { CatalogModifierGroupUpdateManyWithoutCatalogItemModifiersInput } from "./CatalogModifierGroupUpdateManyWithoutCatalogItemModifiersInput";
import { EnumCatalogItemModifierType } from "./EnumCatalogItemModifierType";

@InputType()
class CatalogItemModifierUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string;

  @ApiProperty({
    required: false,
    type: () => MerchantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MerchantWhereUniqueInput)
  @IsOptional()
  @Field(() => MerchantWhereUniqueInput, {
    nullable: true,
  })
  merchant?: MerchantWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  modifierGroupId?: string | null;

  @ApiProperty({
    required: false,
    type: () => CatalogModifierGroupUpdateManyWithoutCatalogItemModifiersInput,
  })
  @ValidateNested()
  @Type(() => CatalogModifierGroupUpdateManyWithoutCatalogItemModifiersInput)
  @IsOptional()
  @Field(() => CatalogModifierGroupUpdateManyWithoutCatalogItemModifiersInput, {
    nullable: true,
  })
  modifierGroups?: CatalogModifierGroupUpdateManyWithoutCatalogItemModifiersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  posIntegrationId?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  suspendedUntil?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumCatalogItemModifierType,
  })
  @IsEnum(EnumCatalogItemModifierType)
  @IsOptional()
  @Field(() => EnumCatalogItemModifierType, {
    nullable: true,
  })
  type?:
    | "ALCOHOL"
    | "FOOD"
    | "REGULAR"
    | "SCHEDULED_SERVICE"
    | "ON_DEMAND_SERVICE";
}

export { CatalogItemModifierUpdateInput as CatalogItemModifierUpdateInput };
