/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CatalogItemService } from "../catalogItem.service";
import { CatalogItemCreateInput } from "./CatalogItemCreateInput";
import { CatalogItemWhereInput } from "./CatalogItemWhereInput";
import { CatalogItemWhereUniqueInput } from "./CatalogItemWhereUniqueInput";
import { CatalogItemFindManyArgs } from "./CatalogItemFindManyArgs";
import { CatalogItemUpdateInput } from "./CatalogItemUpdateInput";
import { CatalogItem } from "./CatalogItem";
import { CatalogCategoryFindManyArgs } from "../../catalogCategory/base/CatalogCategoryFindManyArgs";
import { CatalogCategory } from "../../catalogCategory/base/CatalogCategory";
import { CatalogCategoryWhereUniqueInput } from "../../catalogCategory/base/CatalogCategoryWhereUniqueInput";
import { CatalogModifierGroupFindManyArgs } from "../../catalogModifierGroup/base/CatalogModifierGroupFindManyArgs";
import { CatalogModifierGroup } from "../../catalogModifierGroup/base/CatalogModifierGroup";
import { CatalogModifierGroupWhereUniqueInput } from "../../catalogModifierGroup/base/CatalogModifierGroupWhereUniqueInput";

export class CatalogItemControllerBase {
  constructor(protected readonly service: CatalogItemService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CatalogItem })
  async create(
    @common.Body() data: CatalogItemCreateInput
  ): Promise<CatalogItem> {
    return await this.service.create({
      data: {
        ...data,

        merchant: {
          connect: data.merchant,
        },
      },
      select: {
        categoryId: true,
        createdAt: true,
        description: true,
        id: true,
        images: true,

        merchant: {
          select: {
            id: true,
          },
        },

        name: true,
        ordinal: true,
        posIntegrationId: true,
        price: true,
        supportedFulfillmentModes: true,
        suspendedUntil: true,
        type: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CatalogItem] })
  @ApiNestedQuery(CatalogItemFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<CatalogItem[]> {
    const args = plainToClass(CatalogItemFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        categoryId: true,
        createdAt: true,
        description: true,
        id: true,
        images: true,

        merchant: {
          select: {
            id: true,
          },
        },

        name: true,
        ordinal: true,
        posIntegrationId: true,
        price: true,
        supportedFulfillmentModes: true,
        suspendedUntil: true,
        type: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CatalogItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: CatalogItemWhereUniqueInput
  ): Promise<CatalogItem | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        categoryId: true,
        createdAt: true,
        description: true,
        id: true,
        images: true,

        merchant: {
          select: {
            id: true,
          },
        },

        name: true,
        ordinal: true,
        posIntegrationId: true,
        price: true,
        supportedFulfillmentModes: true,
        suspendedUntil: true,
        type: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CatalogItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: CatalogItemWhereUniqueInput,
    @common.Body() data: CatalogItemUpdateInput
  ): Promise<CatalogItem | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          merchant: {
            connect: data.merchant,
          },
        },
        select: {
          categoryId: true,
          createdAt: true,
          description: true,
          id: true,
          images: true,

          merchant: {
            select: {
              id: true,
            },
          },

          name: true,
          ordinal: true,
          posIntegrationId: true,
          price: true,
          supportedFulfillmentModes: true,
          suspendedUntil: true,
          type: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CatalogItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: CatalogItemWhereUniqueInput
  ): Promise<CatalogItem | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          categoryId: true,
          createdAt: true,
          description: true,
          id: true,
          images: true,

          merchant: {
            select: {
              id: true,
            },
          },

          name: true,
          ordinal: true,
          posIntegrationId: true,
          price: true,
          supportedFulfillmentModes: true,
          suspendedUntil: true,
          type: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/category")
  @ApiNestedQuery(CatalogCategoryFindManyArgs)
  async findManyCategory(
    @common.Req() request: Request,
    @common.Param() params: CatalogItemWhereUniqueInput
  ): Promise<CatalogCategory[]> {
    const query = plainToClass(CatalogCategoryFindManyArgs, request.query);
    const results = await this.service.findCategory(params.id, {
      ...query,
      select: {
        catalogId: true,
        createdAt: true,
        description: true,
        id: true,
        images: true,

        merchant: {
          select: {
            id: true,
          },
        },

        name: true,
        ordinal: true,
        posIntegrationId: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/category")
  async connectCategory(
    @common.Param() params: CatalogItemWhereUniqueInput,
    @common.Body() body: CatalogCategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      category: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/category")
  async updateCategory(
    @common.Param() params: CatalogItemWhereUniqueInput,
    @common.Body() body: CatalogCategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      category: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/category")
  async disconnectCategory(
    @common.Param() params: CatalogItemWhereUniqueInput,
    @common.Body() body: CatalogCategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      category: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/modifierGroups")
  @ApiNestedQuery(CatalogModifierGroupFindManyArgs)
  async findManyModifierGroups(
    @common.Req() request: Request,
    @common.Param() params: CatalogItemWhereUniqueInput
  ): Promise<CatalogModifierGroup[]> {
    const query = plainToClass(CatalogModifierGroupFindManyArgs, request.query);
    const results = await this.service.findModifierGroups(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        itemId: true,
        maximumSelection: true,

        merchant: {
          select: {
            id: true,
          },
        },

        minimumSelection: true,
        name: true,
        posIntegrationId: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/modifierGroups")
  async connectModifierGroups(
    @common.Param() params: CatalogItemWhereUniqueInput,
    @common.Body() body: CatalogModifierGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      modifierGroups: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/modifierGroups")
  async updateModifierGroups(
    @common.Param() params: CatalogItemWhereUniqueInput,
    @common.Body() body: CatalogModifierGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      modifierGroups: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/modifierGroups")
  async disconnectModifierGroups(
    @common.Param() params: CatalogItemWhereUniqueInput,
    @common.Body() body: CatalogModifierGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      modifierGroups: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
