/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  CatalogItem,
  CatalogCategory,
  CatalogModifierGroup,
  Merchant,
} from "@prisma/client";

export class CatalogItemServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CatalogItemCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatalogItemCountArgs>
  ): Promise<number> {
    return this.prisma.catalogItem.count(args);
  }

  async findMany<T extends Prisma.CatalogItemFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatalogItemFindManyArgs>
  ): Promise<CatalogItem[]> {
    return this.prisma.catalogItem.findMany(args);
  }
  async findOne<T extends Prisma.CatalogItemFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatalogItemFindUniqueArgs>
  ): Promise<CatalogItem | null> {
    return this.prisma.catalogItem.findUnique(args);
  }
  async create<T extends Prisma.CatalogItemCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatalogItemCreateArgs>
  ): Promise<CatalogItem> {
    return this.prisma.catalogItem.create<T>(args);
  }
  async update<T extends Prisma.CatalogItemUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatalogItemUpdateArgs>
  ): Promise<CatalogItem> {
    return this.prisma.catalogItem.update<T>(args);
  }
  async delete<T extends Prisma.CatalogItemDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CatalogItemDeleteArgs>
  ): Promise<CatalogItem> {
    return this.prisma.catalogItem.delete(args);
  }

  async findCategory(
    parentId: string,
    args: Prisma.CatalogCategoryFindManyArgs
  ): Promise<CatalogCategory[]> {
    return this.prisma.catalogItem
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .category(args);
  }

  async findModifierGroups(
    parentId: string,
    args: Prisma.CatalogModifierGroupFindManyArgs
  ): Promise<CatalogModifierGroup[]> {
    return this.prisma.catalogItem
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .modifierGroups(args);
  }

  async getMerchant(parentId: string): Promise<Merchant | null> {
    return this.prisma.catalogItem
      .findUnique({
        where: { id: parentId },
      })
      .merchant();
  }
}
