/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CatalogModifierGroupService } from "../catalogModifierGroup.service";
import { CatalogModifierGroupCreateInput } from "./CatalogModifierGroupCreateInput";
import { CatalogModifierGroupWhereInput } from "./CatalogModifierGroupWhereInput";
import { CatalogModifierGroupWhereUniqueInput } from "./CatalogModifierGroupWhereUniqueInput";
import { CatalogModifierGroupFindManyArgs } from "./CatalogModifierGroupFindManyArgs";
import { CatalogModifierGroupUpdateInput } from "./CatalogModifierGroupUpdateInput";
import { CatalogModifierGroup } from "./CatalogModifierGroup";
import { CatalogItemFindManyArgs } from "../../catalogItem/base/CatalogItemFindManyArgs";
import { CatalogItem } from "../../catalogItem/base/CatalogItem";
import { CatalogItemWhereUniqueInput } from "../../catalogItem/base/CatalogItemWhereUniqueInput";
import { CatalogItemModifierFindManyArgs } from "../../catalogItemModifier/base/CatalogItemModifierFindManyArgs";
import { CatalogItemModifier } from "../../catalogItemModifier/base/CatalogItemModifier";
import { CatalogItemModifierWhereUniqueInput } from "../../catalogItemModifier/base/CatalogItemModifierWhereUniqueInput";

export class CatalogModifierGroupControllerBase {
  constructor(protected readonly service: CatalogModifierGroupService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CatalogModifierGroup })
  async create(
    @common.Body() data: CatalogModifierGroupCreateInput
  ): Promise<CatalogModifierGroup> {
    return await this.service.create({
      data: {
        ...data,

        merchant: {
          connect: data.merchant,
        },
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        itemId: true,
        maximumSelection: true,

        merchant: {
          select: {
            id: true,
          },
        },

        minimumSelection: true,
        name: true,
        posIntegrationId: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CatalogModifierGroup] })
  @ApiNestedQuery(CatalogModifierGroupFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<CatalogModifierGroup[]> {
    const args = plainToClass(CatalogModifierGroupFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        itemId: true,
        maximumSelection: true,

        merchant: {
          select: {
            id: true,
          },
        },

        minimumSelection: true,
        name: true,
        posIntegrationId: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CatalogModifierGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: CatalogModifierGroupWhereUniqueInput
  ): Promise<CatalogModifierGroup | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        itemId: true,
        maximumSelection: true,

        merchant: {
          select: {
            id: true,
          },
        },

        minimumSelection: true,
        name: true,
        posIntegrationId: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CatalogModifierGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: CatalogModifierGroupWhereUniqueInput,
    @common.Body() data: CatalogModifierGroupUpdateInput
  ): Promise<CatalogModifierGroup | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          merchant: {
            connect: data.merchant,
          },
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          images: true,
          itemId: true,
          maximumSelection: true,

          merchant: {
            select: {
              id: true,
            },
          },

          minimumSelection: true,
          name: true,
          posIntegrationId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CatalogModifierGroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: CatalogModifierGroupWhereUniqueInput
  ): Promise<CatalogModifierGroup | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          images: true,
          itemId: true,
          maximumSelection: true,

          merchant: {
            select: {
              id: true,
            },
          },

          minimumSelection: true,
          name: true,
          posIntegrationId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/items")
  @ApiNestedQuery(CatalogItemFindManyArgs)
  async findManyItems(
    @common.Req() request: Request,
    @common.Param() params: CatalogModifierGroupWhereUniqueInput
  ): Promise<CatalogItem[]> {
    const query = plainToClass(CatalogItemFindManyArgs, request.query);
    const results = await this.service.findItems(params.id, {
      ...query,
      select: {
        categoryId: true,
        createdAt: true,
        description: true,
        id: true,
        images: true,

        merchant: {
          select: {
            id: true,
          },
        },

        name: true,
        ordinal: true,
        posIntegrationId: true,
        price: true,
        supportedFulfillmentModes: true,
        suspendedUntil: true,
        type: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/items")
  async connectItems(
    @common.Param() params: CatalogModifierGroupWhereUniqueInput,
    @common.Body() body: CatalogItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      items: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/items")
  async updateItems(
    @common.Param() params: CatalogModifierGroupWhereUniqueInput,
    @common.Body() body: CatalogItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      items: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/items")
  async disconnectItems(
    @common.Param() params: CatalogModifierGroupWhereUniqueInput,
    @common.Body() body: CatalogItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      items: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/modifiers")
  @ApiNestedQuery(CatalogItemModifierFindManyArgs)
  async findManyModifiers(
    @common.Req() request: Request,
    @common.Param() params: CatalogModifierGroupWhereUniqueInput
  ): Promise<CatalogItemModifier[]> {
    const query = plainToClass(CatalogItemModifierFindManyArgs, request.query);
    const results = await this.service.findModifiers(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        merchant: {
          select: {
            id: true,
          },
        },

        modifierGroupId: true,
        name: true,
        posIntegrationId: true,
        price: true,
        suspendedUntil: true,
        type: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/modifiers")
  async connectModifiers(
    @common.Param() params: CatalogModifierGroupWhereUniqueInput,
    @common.Body() body: CatalogItemModifierWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      modifiers: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/modifiers")
  async updateModifiers(
    @common.Param() params: CatalogModifierGroupWhereUniqueInput,
    @common.Body() body: CatalogItemModifierWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      modifiers: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/modifiers")
  async disconnectModifiers(
    @common.Param() params: CatalogModifierGroupWhereUniqueInput,
    @common.Body() body: CatalogItemModifierWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      modifiers: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
